export const buttons = [
  { value: "AC", id: "clear", className: "jumbo" },
  { value: "/", id: "divide", className: "operators" },
  { value: "*", id: "multiply", className: "operators" },
  { value: "7", id: "seven" },
  { value: "8", id: "eight" },
  { value: "9", id: "nine" },
  { value: "-", id: "subtract", className: "operators" },
  { value: "4", id: "four" },
  { value: "5", id: "five" },
  { value: "6", id: "six" },
  { value: "+", id: "add", className: "operators" },
  { value: "1", id: "one" },
  { value: "2", id: "two" },
  { value: "3", id: "three" },
  { value: "0", id: "zero", className: "jumbo" },
  { value: ".", id: "decimal" },
  { value: "=", id: "equals", className: "equal" },
];
